package com.isansys.common.enums;

public enum HttpOperationType
{
    INVALID,

    // HTTP Posts
    PATIENT_DETAILS,

    DEVICE_INFO,
    START_DEVICE_SESSION,
    END_DEVICE_SESSION,

    START_PATIENT_SESSION,
    END_PATIENT_SESSION,

    LIFETOUCH_HEART_RATE,
    LIFETOUCH_RESPIRATION_RATE,
    LIFETOUCH_HEART_BEAT,
    LIFETOUCH_SETUP_MODE_SAMPLE,
    LIFETOUCH_BATTERY,
    LIFETOUCH_PATIENT_ORIENTATION,
    LIFETOUCH_RAW_ACCELEROMETER_MODE_SAMPLE,

    LIFETEMP_TEMPERATURE,
    LIFETEMP_BATTERY,

    PULSE_OX_MEASUREMENT,
    PULSE_OX_INTERMEDIATE_MEASUREMENT,
    PULSE_OX_SETUP_MODE_SAMPLE,
    PULSE_OX_BATTERY,

    DO_NOT_USE__WAS_LIFEOX_MEASUREMENT,
    DO_NOT_USE__WAS_LIFEOX_INTERMEDIATE_MEASUREMENT,
    DO_NOT_USE__WAS_LIFEOX_SETUP_MODE_SAMPLE,
    DO_NOT_USE__WAS_LIFEOX_BATTERY,

    BLOOD_PRESSURE_MEASUREMENT,
    BLOOD_PRESSURE_BATTERY,

    WEIGHT_SCALE_MEASUREMENT,
    WEIGHT_SCALE_BATTERY,

    CONNECTION_EVENT,

    SERVER_PING,
    CHECK_DEVICE_DETAILS,
    CHECK_PATIENT_ID,

    // HTTP Gets
    BED_DETAILS_LIST,
    WARD_DETAILS_LIST,

    CHECK_START_PATIENT_SESSION,
    CHECK_START_DEVICE_SESSION,
    CHECK_END_DEVICE_SESSION,
    CHECK_END_PATIENT_SESSION,

    // Manually Entered Vital Signs
    MANUALLY_ENTERED_HEART_RATES,
    MANUALLY_ENTERED_RESPIRATION_RATES,
    MANUALLY_ENTERED_TEMPERATURES,
    MANUALLY_ENTERED_SPO2_MEASUREMENTS,
    MANUALLY_ENTERED_BLOOD_PRESSURE_MEASUREMENTS,
    MANUALLY_ENTERED_WEIGHT_MEASUREMENTS,
    MANUALLY_ENTERED_CONSCIOUSNESS_LEVELS,
    MANUALLY_ENTERED_SUPPLEMENTAL_OXYGEN_LEVELS,
    MANUALLY_ENTERED_ANNOTATIONS,
    MANUALLY_ENTERED_CAPILLARY_REFILL_TIME,
    MANUALLY_ENTERED_RESPIRATION_DISTRESS,
    MANUALLY_ENTERED_FAMILY_OR_NURSE_CONCERN,
    MANUALLY_ENTERED_URINE_OUTPUT,

    EARLY_WARNING_SCORES,

    // Has all the data for a Patient Session been synced to the Server
    PATIENT_SESSION_FULLY_SYNCED,

    // Get Default Threshold Sets
    GET_DEFAULT_EARLY_WARNING_SCORES_LIST,

    // Get Latest Firmware version numbers
    GET_DEVICE_FIRMWARE_VERSION_LIST,
    DOWNLOAD_DEVICE_FIRMWARE_BY_ID,

    // Get Gateway Config from Server
    GET_GATEWAY_CONFIG,

    // Logs of Start/Stop times for Setup Mode
    SETUP_MODE_LOG,

    // Auditable events
    AUDITABLE_EVENTS,

    // Get Server Configurable Text from Server
    GET_SERVER_CONFIGURABLE_TEXT,

    // Get customer specific MQTT Certificate
    GET_MQTT_CERTIFICATE,

    // Get Viewable Web Pages from Server
    GET_VIEWABLE_WEBPAGES,
}

