package com.isansys.common.enums;

public enum QueryType
{
    // Lifetouch
    LIFETOUCH_HEART_BEATS,
    LIFETOUCH_RESPIRATION_RATES,
    LIFETOUCH_SETUP_MODE_RAW_SAMPLES,
    LIFETOUCH_HEART_RATES,
    LIFETOUCH_BATTERY_MEASUREMENTS,
    LIFETOUCH_PATIENT_ORIENTATIONS,
    LIFETOUCH_RAW_ACCELEROMETER_MODE_RAW_SAMPLES,

    // Lifetemp
    LIFETEMP_TEMPERATURE_MEASUREMENTS,
    LIFETEMP_BATTERY_MEASUREMENTS,

    // Oximeter
    PULSE_OX_MEASUREMENTS,
    PULSE_OX_INTERMEDIATE_MEASUREMENTS,
    PULSE_OX_SETUP_MODE_SAMPLES,
    PULSE_OX_BATTERY_MEASUREMENTS,

    // Blood Pressure
    BLOOD_PRESSURE_MEASUREMENTS,
    BLOOD_PRESSURE_BATTERY_MEASUREMENTS,

    // Weight Pressure
    WEIGHT_SCALE_MEASUREMENTS,
    WEIGHT_SCALE_BATTERY_MEASUREMENTS,

    // Patient Details
    PATIENT_DETAILS,

    // Device Session Details
    DEVICE_SESSIONS,

    // Device Info Details
    DEVICE_INFO,

    // Patient Session Details
    PATIENT_SESSIONS,
    PATIENT_SESSION_FULLY_SYNCED,

    // Connection Events
    CONNECTION_EVENTS,

    // Diagnostics
    GATEWAY_STARTUP_TIMES,
    UI_STARTUP_TIMES,

    // Manually Entered Vital Signs
    MANUALLY_ENTERED_HEART_RATES,
    MANUALLY_ENTERED_RESPIRATION_RATES,
    MANUALLY_ENTERED_TEMPERATURES,
    MANUALLY_ENTERED_SPO2_MEASUREMENTS,
    MANUALLY_ENTERED_BLOOD_PRESSURE_MEASUREMENTS,
    MANUALLY_ENTERED_WEIGHT_MEASUREMENTS,
    MANUALLY_ENTERED_CONSCIOUSNESS_LEVEL_MEASUREMENTS,
    MANUALLY_ENTERED_SUPPLEMENTAL_OXYGEN_LEVEL_MEASUREMENTS,
    MANUALLY_ENTERED_ANNOTATIONS,
    MANUALLY_ENTERED_CAPILLARY_REFILL_TIMES,
    MANUALLY_ENTERED_RESPIRATION_DISTRESS,
    MANUALLY_ENTERED_FAMILY_OR_NURSE_CONCERN,
    MANUALLY_ENTERED_URINE_OUTPUT,

    // Early Warning Scores
    EARLY_WARNING_SCORES,

    // Early Warning Score Threshold Levels
    EARLY_WARNING_SCORE_THRESHOLD_SETS,
    EARLY_WARNING_SCORE_THRESHOLD_SET_AGE_BLOCK_DETAILS,
    EARLY_WARNING_SCORE_THRESHOLD_SET_LEVELS,
    EARLY_WARNING_SCORE_THRESHOLD_SET_COLOURS,

    // Setup Mode Logs
    LIFETOUCH_SETUP_MODE_LOGS,
    NONIN_SETUP_MODE_LOGS,
    ALL_SETUP_MODE_LOGS,

    // Audit trail
    ALL_AUDITABLE_EVENTS,

    // Server Configurable Text
    SERVER_CONFIGURABLE_TEXT,

    WARDS,
    BEDS,

    // Webpages that the user can visit
    WEBPAGES,
}