package com.isansys.patientgateway.serverlink.constants;

public enum ServerSyncingDataUploadPoint
{
    NO_MORE_DATA_TO_SYNC,

    // Patient Session Information
    PATIENT_DETAILS_DATA,
    DEVICE_INFO_DATA,

    // Patient Details Information
    START_PATIENT_SESSION,
    START_DEVICE_SESSION,
    END_DEVICE_SESSION,
    END_PATIENT_SESSION,

    // Session Data Information
    CONNECTION_EVENT,

    // Current Session data
    LIFETOUCH_HEART_RATE,
    LIFETOUCH_HEART_BEAT,
    LIFETOUCH_RESPIRATION_RATE,
    LIFETOUCH_SETUP_MODE,
    LIFETOUCH_BATTERY_MEASUREMENT,
    LIFETOUCH_PATIENT_ORIENTATION,
    LIFETOUCH_RAW_ACCELEROMETER_MODE,

    LIFETEMP_TEMPERATURE_MEASUREMENT,
    LIFETEMP_BATTERY_MEASUREMENT,

    PULSE_OX_MEASUREMENT,
    PULSE_OX_INTERMEDIATE_MEASUREMENT,
    PULSE_OX_SETUP_MODE,
    PULSE_OX_BATTERY_MEASUREMENT,

    BLOOD_PRESSURE_MEASUREMENT,
    BLOOD_PRESSURE_BATTERY_MEASUREMENT,

    WEIGHT_SCALE_MEASUREMENT,
    WEIGHT_SCALE_BATTERY_MEASUREMENT,

    MANUALLY_ENTERED_HEART_RATES,
    MANUALLY_ENTERED_RESPIRATION_RATES,
    MANUALLY_ENTERED_TEMPERATURE_MEASUREMENTS,
    MANUALLY_ENTERED_OXIMETER_MEASUREMENTS,
    MANUALLY_ENTERED_BLOOD_PRESSURE_MEASUREMENTS,
    MANUALLY_ENTERED_WEIGHT_MEASUREMENTS,
    MANUALLY_ENTERED_CONSCIOUSNESS_LEVEL_MEASUREMENTS,
    MANUALLY_ENTERED_SUPPLEMENTAL_OXYGEN_LEVEL_MEASUREMENTS,
    MANUALLY_ENTERED_ANNOTATIONS,
    MANUALLY_ENTERED_CAPILLARY_REFILL_TIMES,
    MANUALLY_ENTERED_RESPIRATION_DISTRESS,
    MANUALLY_ENTERED_FAMILY_OR_NURSE_CONCERN,
    MANUALLY_ENTERED_URINE_OUTPUT,

    EARLY_WARNING_SCORES,

    SETUP_MODE_LOGS,

    AUDITABLE_EVENTS,

    FULLY_SYNCED_SESSIONS,

    // Old Session Data Information
    HISTORICAL_CONNECTION_EVENT,

    // Old Session Data
    HISTORICAL_LIFETOUCH_HEART_RATE,
    HISTORICAL_LIFETOUCH_HEART_BEAT,
    HISTORICAL_LIFETOUCH_RESPIRATION_RATE,
    HISTORICAL_LIFETOUCH_SETUP_MODE,
    HISTORICAL_LIFETOUCH_BATTERY_MEASUREMENT,
    HISTORICAL_LIFETOUCH_PATIENT_ORIENTATION,
    HISTORICAL_LIFETOUCH_RAW_ACCELEROMETER_MODE,

    HISTORICAL_LIFETEMP_TEMPERATURE_MEASUREMENT,
    HISTORICAL_LIFETEMP_BATTERY_MEASUREMENT,

    HISTORICAL_PULSE_OX_MEASUREMENT,
    HISTORICAL_PULSE_OX_INTERMEDIATE_MEASUREMENT,
    HISTORICAL_PULSE_OX_SETUP_MODE,
    HISTORICAL_PULSE_OX_BATTERY_MEASUREMENT,

    HISTORICAL_BLOOD_PRESSURE_MEASUREMENT,
    HISTORICAL_BLOOD_PRESSURE_BATTERY_MEASUREMENT,

    HISTORICAL_WEIGHT_SCALE_MEASUREMENT,
    HISTORICAL_WEIGHT_SCALE_BATTERY_MEASUREMENT,

    HISTORICAL_MANUALLY_ENTERED_HEART_RATES,
    HISTORICAL_MANUALLY_ENTERED_RESPIRATION_RATES,
    HISTORICAL_MANUALLY_ENTERED_TEMPERATURE_MEASUREMENTS,
    HISTORICAL_MANUALLY_ENTERED_OXIMETER_MEASUREMENTS,
    HISTORICAL_MANUALLY_ENTERED_BLOOD_PRESSURE_MEASUREMENTS,
    HISTORICAL_MANUALLY_ENTERED_WEIGHT_MEASUREMENTS,
    HISTORICAL_MANUALLY_ENTERED_CONSCIOUSNESS_LEVEL_MEASUREMENTS,
    HISTORICAL_MANUALLY_ENTERED_SUPPLEMENTAL_OXYGEN_LEVEL_MEASUREMENTS,
    HISTORICAL_MANUALLY_ENTERED_ANNOTATIONS,
    HISTORICAL_MANUALLY_ENTERED_CAPILLARY_REFILL_TIMES,
    HISTORICAL_MANUALLY_ENTERED_RESPIRATION_DISTRESS,
    HISTORICAL_MANUALLY_ENTERED_FAMILY_OR_NURSE_CONCERN,
    HISTORICAL_MANUALLY_ENTERED_URINE_OUTPUT,

    HISTORICAL_SETUP_MODE_LOGS,

    HISTORICAL_EARLY_WARNING_SCORES,
}
