package com.isansys.patientgateway.serverlink;

public enum MessageType
{
    WEBSERVICE_CALL,
    WEBSERVICE_RESPONSE,

    REPORT_DEVICE_LEADS_OFF,

    ENABLE_DEVICE_SETUP_MODE,
    REPORT_DEVICE_SETUP_MODE_ENABLE_STATUS,
    DEVICE_SETUP_MODE_DATA,

    ENABLE_DEVICE_RAW_ACCELEROMETER_MODE,
    REPORT_DEVICE_RAW_ACCELEROMETER_MODE_ENABLE_STATUS,
    DEVICE_RAW_ACCELEROMETER_MODE_DATA,

    GET_GATEWAY_STATUS,
    REPORT_GATEWAY_STATUS,

    GET_FEATURES_ENABLED,
    REPORT_FEATURES_ENABLED,

    GET_DATABASE_SYNC_STATUS,
    REPORT_DATABASE_SYNC_STATUS,

    REQUEST_NAME_FROM_HOSPITAL_PATIENT_ID,

    SIMULATE_USER_QR_CODE,
    SIMULATE_ADMIN_QR_CODE,
    SIMULATE_FEATURE_ENABLE_QR_CODE,

    NTP_TIME_SYNC,
    EXPORT_DB,
    EMPTY_LOCAL_DATABASE,

    ENABLE_PATIENT_NAME_LOOKUP,
    DISABLE_PATIENT_NAME_LOOKUP,

    ENABLE_PERIODIC_SETUP_MODE,
    DISABLE_PERIODIC_SETUP_MODE,

    ENABLE_DUMMY_DATA_MODE,
    DISABLE_DUMMY_DATA_MODE,

    ENABLE_NONIN_TURN_ON_BY_INSERTING_FINGER,
    DISABLE_NONIN_TURN_ON_BY_INSERTING_FINGER,

    ENABLE_UNPLUGGED_OVERLAY,
    DISABLE_UNPLUGGED_OVERLAY,

    ENABLE_NIGHT_MODE,
    DISABLE_NIGHT_MODE,

    ENABLE_CSV_OUTPUT,
    DISABLE_CSV_OUTPUT,

    ENABLE_SIMPLE_HEART_RATE_ALGORITHM,
    DISABLE_SIMPLE_HEART_RATE_ALGORITHM,

    GET_DEVICE_INFOS,
    REPORT_DEVICE_INFOS,

    RESET_GATEWAY_AND_UI_RUN_COUNTERS,
    SET_JSON_ARRAY_SIZE,
    SET_NUMBER_OF_DUMMY_DATA_MODE_MEASUREMENTS_PER_TICK,
    SET_SETUP_MODE_TIME_IN_SECONDS,
    SET_NUMBER_OF_INVALID_NONIN_INTERMEDIATE_MEASUREMENTS_BEFORE_MINUTE_MARKED_AS_INVALID,
    HANDLE_PATIENT_DETAILS_RECEIVED_FROM_HOSPITAL_PATIENT_ID_LOOKUP,
    RESET_SERVER_SYNC_STATUS,
    SEND_SERVER_PING,

    SET_DISPLAY_TIMEOUT_IN_SECONDS,
    SET_DISPLAY_TIMEOUT_APPLIES_TO_PATIENT_VITALS


}
