package com.isansys.patientgateway.serverlink.constants;

public enum ServerStatusReceivedCode
{
    RESPONSE_CODE__VALID,
    //Device Info
    RESPONSE_CODE__DEVICE_INFO__NO_DEVICE_TYPE,
    RESPONSE_CODE__DEVICE_INFO__NO_HUMAN_READABLE_DEVICE_ID,
    RESPONSE_CODE__DEVICE_INFO__UNKNOWN_ERROR,
    // Device History
    RESPONSE_CODE__DEVICE_HISTORY__NO_DEVICE_ID,
    RESPONSE_CODE__DEVICE_HISTORY__UNKNOWN_ERROR,
    // Patient Session
    RESPONSE_CODE__PATIENT_SESSION__NO_PATIENT_DETAILS_ID,
    RESPONSE_CODE__PATIENT_SESSION__UNKNOWN_ERROR,
    // Device Session
    RESPONSE_CODE__DEVICE_SESSION__NO_PATIENT_SESSION_ID,
    RESPONSE_CODE__DEVICE_SESSION__NO_DEVICE_ID,
    RESPONSE_CODE__DEVICE_SESSION__UNKNOWN_ERROR, 
    // User Details
    RESPONSE_CODE__USER_DETAILS__NO_EMAIL_NO_USER_NAME,
    RESPONSE_CODE__USER_DETAILS__NO_USER,
    RESPONSE_CODE__USER_DETAILS__NO_EMAIL,
    RESPONSE_CODE__USER_DETAILS__EMAIL_EXISTS,
    RESPONSE_CODE__USER_DETAILS__USER_EXISTS,
    RESPONSE_CODE__USER_DETAILS__USER_EXISTS_EMAIL_EXISTS,
    RESPONSE_CODE__USER_DETAILS__UNKNOWN_ERROR,
    // Ward Details
    RESPONSE_CODE__WARD_DETAILS__NO_WARD_LOCATION,
    RESPONSE_CODE__WARD_DETAILS__WARD_EXISTS,
    RESPONSE_CODE__WARD_DETAILS__UNKNOWN_ERROR, 
    // Bed Details
    RESPONSE_CODE__BED_DETAILS__NO_BED_NAME,
    RESPONSE_CODE__BED_DETAILS__BED_EXISTS,
    RESPONSE_CODE__BED_DETAILS__UNKNOWN_ERROR,
    // Patient Details
    RESPONSE_CODE__PATIENT_DETAILS__NO_HOSPITAL_PATIENT_ID,
    RESPONSE_CODE__PATIENT_DETAILS__NO_BED_ID,
    RESPONSE_CODE__PATIENT_DETAILS__AGE_BLOCK,
    RESPONSE_CODE__PATIENT_DETAILS__HOSPITAL_PATIENT_ID_EXISTS,
    RESPONSE_CODE__PATIENT_DETAILS__UNKNOWN_ERROR,

    //Lifetouch
    RESPONSE_CODE__LIFETOUCH_BATTERY__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_BATTERY__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETOUCH_HEARTRATE__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_HEARTRATE__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETOUCH_SETUPMODE__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_SETUPMODE__UNKNOWN_ERROR,

    //Lifetemp
    RESPONSE_CODE__LIFETEMP_BATTERY__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETEMP_BATTERY__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETEMP_TEMPERATURE__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETEMP_TEMPERATURE__UNKNOWN_ERROR,

    // Oximeter
    RESPONSE_CODE__OXIMETER_BATTERY__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_BATTERY__UNKNOWN_ERROR,

    RESPONSE_CODE__OXIMETER_INTERMEDIATE__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_INTERMEDIATE__UNKNOWN_ERROR,

    RESPONSE_CODE__OXIMETER_MEASUREMENT__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_MEASUREMENT__UNKNOWN_ERROR,

    // BloodPressure
    RESPONSE_CODE__BLOODPRESSURE_BATTERY__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__BLOODPRESSURE_BATTERY__UNKNOWN_ERROR,

    RESPONSE_CODE__BLOODPRESSURE_MEASUREMENTS__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__BLOODPRESSURE_MEASUREMENTS__UNKNOWN_ERROR,

    // Other Services error
    // measurements list by device session id
    RESPONSE_CODE__LIFETOUCH_BATTERY__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_BATTERY__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_HEARTRATE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_HEARTRATE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_SETUPMODE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETOUCH_SETUPMODE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETEMP_BATTERY__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETEMP_BATTERY__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETEMP_TEMPERATURE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFETEMP_TEMPERATURE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,

    RESPONSE_CODE__OXIMETER_BATTERY__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_BATTERY__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_INTERMEDIATE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_INTERMEDIATE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_MEASUREMENT__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_MEASUREMENT__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_SETUPMODE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__OXIMETER_SETUPMODE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,

    RESPONSE_CODE__BLOODPRESSURE_BATTERY__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__BLOODPRESSURE_BATTERY__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__BLOODPRESSURE__MEASUREMENTS__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__BLOODPRESSURE__MEASUREMENTS__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,

    // Device Status
    RESPONSE_CODE__DEVICE_STATUS__DEVICE_DOES_NOT_EXIST,
    RESPONSE_CODE__DEVICE_STATUS__UNKNOWN_ERROR,

    // Gateway Status
    RESPONSE_CODE__GATEWAY_STATUS__UNKNOWN_ERROR,

    // Patient Status
    RESPONSE_CODE__PATIENT_STATUS__UNKNOWN_ERROR,

    // Patient Gateway Software Update
    RESPONSE_CODE__PATIENT_GATEWAY_SOFTWARE_UPDATE__UNKNOWN_ERROR,

    // User Interface Software Update
    RESPONSE_CODE__USER_INTERFACE_SOFTWARE_UPDATE__UNKNOWN_ERROR,

    RESPONSE_CODE__CONNECTION_EVENT__UNKNOWN_ERROR,

    RESPONSE_CODE__BLOODPRESSURE_BATTERY__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__BLOODPRESSURE_BATTERY__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__BLOODPRESSURE_BATTERY__OBJECT_LIST_NULL,

    RESPONSE_CODE__BLOODPRESSURE_MEASUREMENTS__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__BLOODPRESSURE_MEASUREMENTS__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__BLOODPRESSURE_MEASUREMENTS__OBJECT_LIST_NULL,
    RESPONSE_CODE__BLOODPRESSURE_MEASUREMENTS__LIST_BY_PATIENT_SESSION_ID__ERROR,

    RESPONSE_CODE__LIFETEMP_BATTERY__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETEMP_BATTERY__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETEMP_BATTERY__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__LIFETEMP_BATTERY__LIST_BY_PATIENT_SESSION_ID__ERROR,

    RESPONSE_CODE__LIFETEMP_TEMPERATURE__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETEMP_TEMPERATURE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETEMP_TEMPERATURE__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__LIFETEMP_TEMPERATURE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETOUCH_BATTERY__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETOUCH_BATTERY__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETOUCH_BATTERY__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__LIFETOUCH_BATTERY__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,

    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETOUCH_HEARTBEAT__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__LIFETOUCH_HEARTRATE__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETOUCH_HEARTRATE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETOUCH_HEARTRATE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_HEARTRATE__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_RESPIRATIONRATE__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__LIFETOUCH_SETUPMODE__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFETOUCH_SETUPMODE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFETOUCH_SETUPMODE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFETOUCH_SETUPMODE__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__OXIMETER_BATTERY__OBJECT_LIST_NULL,
    RESPONSE_CODE__OXIMETER_BATTERY__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__OXIMETER_BATTERY__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_BATTERY__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__OXIMETER_INTERMEDIATE__OBJECT_LIST_NULL,
    RESPONSE_CODE__OXIMETER_INTERMEDIATE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__OXIMETER_INTERMEDIATE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_INTERMEDIATE__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__OXIMETER_MEASUREMENT__OBJECT_LIST_NULL,
    RESPONSE_CODE__OXIMETER_MEASUREMENT__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__OXIMETER_MEASUREMENT__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_MEASUREMENT__EXECUTE_SELECT_QUERY_ERROR,

    RESPONSE_CODE__OXIMETER_SETUPMODE__OBJECT_LIST_NULL,
    RESPONSE_CODE__OXIMETER_SETUPMODE__EXECUTE_INSERT_QUERY_ERROR, 
    RESPONSE_CODE__OXIMETER_SETUPMODE__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__OXIMETER_SETUPMODE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__OXIMETER_SETUPMODE__UNKNOWN_ERROR,

    RESPONSE_CODE__DEVICE_SESSION__OBJECT_LIST_NULL,
    RESPONSE_CODE__DEVICE_SESSION__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__DEVICE_SESSION__UPDATE_ERROR,

    RESPONSE_CODE__PATIENT_SESSION__NO_PATIENT_SESSION_ID,
    RESPONSE_CODE__PATIENT_SESSION__UPDATE_ERROR,
    RESPONSE_CODE__PATIENT_SESSION__NO_PATIENT_SESSION_TIME,

    RESPONSE_CODE__DEVICE_HISTORY__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__DEVICE_HISTORY__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__DEVICE_HISTORY__OBJECT_LIST_NULL,
    RESPONSE_CODE__DEVICE_INFO__OBJECT_LIST_NULL,

    RESPONSE_CODE__MANUALLY_ENTERED_MEASUREMENTS__NO_PATIENT_SESSION_ID,
    RESPONSE_CODE__MANUALLY_ENTERED_MEASUREMENTS__UNKNOWN_ERROR,
    PATIENT_SESSION_SET_GATEWAY_DATA_COMPLETE_ERROR,
    RESPONSE_CODE__LIFEOX_BATTERY__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_BATTERY__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFEOX_BATTERY__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_BATTERY__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFEOX_BATTERY__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFEOX_MEASUREMENT__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFEOX_SETUPMODE__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_SETUPMODE__OBJECT_LIST_NULL,
    RESPONSE_CODE__LIFEOX_SETUPMODE__EXECUTE_SELECT_QUERY_ERROR,
    RESPONSE_CODE__LIFEOX_SETUPMODE__LIST_BY_DEVICE_SESSION_ID__NO_DEVICE_SESSION_ID,
    RESPONSE_CODE__LIFEOX_SETUPMODE__LIST_BY_DEVICE_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_SETUPMODE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__LIFEOX_SETUPMODE__EXECUTE_INSERT_QUERY_ERROR,
    RESPONSE_CODE__LIFEOX_INTERMEDIATE__LIST_BY_PATIENT_SESSION_ID__UNKNOWN_ERROR,
    RESPONSE_CODE__EWS_MEASUREMENT__NO_PATIENT_SESSION_ID,
    RESPONSE_CODE__EWS_MEASUREMENT__UNKNOWN_ERROR
}
