package com.isansys.common.enums;

public enum VideoCallStatus
{
    VIDEO_CALL_STATUS__INVALID,
    VIDEO_CALL_STATUS__NONE,
    VIDEO_CALL_STATUS__IDLE,
    VIDEO_CALL_STATUS__SERVER_CALLING_GATEWAY__GATEWAY_RINGING,
    VIDEO_CALL_STATUS__SERVER_CALLING_GATEWAY__GATEWAY_DECLINED,
    VIDEO_CALL_STATUS__MISSED_CALL,
    VIDEO_CALL_STATUS__CONNECTING,
    VIDEO_CALL_STATUS__IN_MEETING,
    VIDEO_CALL_STATUS__DISCONNECTING,
    VIDEO_CALL_STATUS__RECONNECTING,
    VIDEO_CALL_STATUS__FAILED,
    VIDEO_CALL_STATUS__GATEWAY_TO_SERVER_CALL_RINGING,
    VIDEO_CALL_STATUS__GATEWAY_CALLING_SERVER__GATEWAY_CANCELLED,
    VIDEO_CALL_STATUS__UNKNOWN,
    VIDEO_CALL_STATUS__SERVER_TO_SERVER_CALL_RINGING,                                   // Not used on Gateway
    VIDEO_CALL_STATUS__SERVER_TO_SERVER_CALL_DECLINED,                                  // Not used on Gateway
}
